{% set name = "pytimeparse" %}
{% set version = "1.1.7" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "51b641bcd435e0cb6b9701ed79cf7ee97fa6bf2dbb5d41baa16e5486e5d9b17a" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pytimeparse

about:
  home: https://github.com/wroberts/pytimeparse
  license: MIT
  license_family: MIT
  license_file: pytimeparse/timeparse.py  # License in source
  summary: 'A small Python library to parse various kinds of time expressions'
  doc_url: https://github.com/wroberts/pytimeparse
  dev_url: https://github.com/wroberts/pytimeparse

extra:
  recipe-maintainers:
    - pmlandwehr
