# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vOxt5lKviWwOMFmGE4Jmdh7HNTtGkIBCAfEqLmthUF8PPCqnujaNAmQSbOBa2URl8jRbFfA2Pcp/eaz0E3pjrXHmDT2VB4mhquPTlK36+N1CGjvsu+AVckS3WmN88A8s6h+8UY4kuUUKl+Pi4npvoqvY3jBmCsNXMbSoHx9JKdjBler+mWclKj0cpvKHsneP5/RnCpezGQlE+NSRQDO0Gk1VGtKrT1W757NWT5kaBDecKt6zWBn+T3fNIMGPY9RB0OYgnl3oR0xTL91j5+T2J8cZ9ZhW63d7U/iG/x5HU3Z5DdskqY/6hHtK9avbGCNgCDqzVc43+S6E9F+bglYDVKNZyzURN0M+kbvpY2fmj4oPKAwJXXZ4Pon/8bvhniAPCVdL3jj0Js6ZBi14qZ2BjlC2vF504aD5xeYyW11stoiP+l5WW0DS1XQhkYXq2rLyOFkJoK8l+UJhWlTKBNGokMdbGV4fIFxgzjSabA/ddpxN9ZrTBAj3ysEDQtfKQlgXZGHTjPqDZitPQgrzQVYn2MEMN03fC7ffwSt+HQ163X+BSHrP053O1p/tlSSjAgvdLCM2IMFF57rrnTGsVZAftCfYfa3UahXQMM1GpxiELgsWwo7OE0YOCF+5ZyW+KNB25e6OS3d3v/ZvztFtuUQzUQ2YYNEDlDDFZZ9KEKtpejU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
