travis:
  secure:
    BINSTAR_TOKEN: gV9Hs5fu2L2Z8VdOr97uNoAimHmzxnSK1fCkHq76fv2vADoXUx/1ijlaQzWFVmlJ05xtmhM+/iia6oCowbA0uDu+bA5Pr4eY7q2hbX+tjzBt8espSLK4KR66bquTPgp77FkXmgYsJfvieB5Fun3YJfPEUiaWpzIFYzgmeaDjDIRjbafeqSxIQ+JSsX89VKe6N+6bxM0j1+z19ZbsJJhm5/HhkH8n5aunkBembmF1uFOGAibvg5GhU35InT+fHkcqDQfTBLOIFLD4FxRmtopXna87ufl/25AN+8GDPUfLMZ0KMeeAF0KgvFLdePkxmWgVOVmcVHPPTdpSlha3FaoRImXwtHh9u5ITxJt4TCVYBckdqcuF0reytRXYnYbMcjTLTBjJBwenhflAwkbR8jlK7o9W2b8FaYM13MpE32W9iT4ZsWWTk25AVi9CIpqMvIz9ZzY7hue55KlqT6yGnB7WbrpFn0DSc01Ar7cHKgyk/K+zcH+YtZAMoAGQ1K1aa9+LOFAd+iX19/uK33URzPhLJNkeoSvLQbljDOSJzcSXtrTxFF1V1f7zqOyFmOrJAAAw9uZPYW5V26cplceXqfDgd/PQwEZ44zl84XyETykgYKyLizC87DHQ9iPH7zq5lW9cMUWhiaISS6/z1Atw9jDKf5nrFYHf9R1Z9mdqiEcdbeA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
