travis:
  secure:
    BINSTAR_TOKEN: vOxt5lKviWwOMFmGE4Jmdh7HNTtGkIBCAfEqLmthUF8PPCqnujaNAmQSbOBa2URl8jRbFfA2Pcp/eaz0E3pjrXHmDT2VB4mhquPTlK36+N1CGjvsu+AVckS3WmN88A8s6h+8UY4kuUUKl+Pi4npvoqvY3jBmCsNXMbSoHx9JKdjBler+mWclKj0cpvKHsneP5/RnCpezGQlE+NSRQDO0Gk1VGtKrT1W757NWT5kaBDecKt6zWBn+T3fNIMGPY9RB0OYgnl3oR0xTL91j5+T2J8cZ9ZhW63d7U/iG/x5HU3Z5DdskqY/6hHtK9avbGCNgCDqzVc43+S6E9F+bglYDVKNZyzURN0M+kbvpY2fmj4oPKAwJXXZ4Pon/8bvhniAPCVdL3jj0Js6ZBi14qZ2BjlC2vF504aD5xeYyW11stoiP+l5WW0DS1XQhkYXq2rLyOFkJoK8l+UJhWlTKBNGokMdbGV4fIFxgzjSabA/ddpxN9ZrTBAj3ysEDQtfKQlgXZGHTjPqDZitPQgrzQVYn2MEMN03fC7ffwSt+HQ163X+BSHrP053O1p/tlSSjAgvdLCM2IMFF57rrnTGsVZAftCfYfa3UahXQMM1GpxiELgsWwo7OE0YOCF+5ZyW+KNB25e6OS3d3v/ZvztFtuUQzUQ2YYNEDlDDFZZ9KEKtpejU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
