travis:
  secure:
    BINSTAR_TOKEN: kNf+1vFjrQhhXB7D+2Ygg80xvTiHgUIfvBa9/rSIMeZlgCL11TyyxK0hRv8ddPfO6iTtJNI3pxGdqH/PIsJqALrubBv2FsFwUpe5zhVGxoKfxq8S1zYiGe9f3mK2z4DJeK6qD0S3CE3BpcP3w9ueiTANkf35JdnN6It2nXCpA+EHwTZeSkGzJlrfuvre+B/LHwpZg0uTvCfJljojCh6jN6YsTP7GSGxvHqVXxy5WZYF6cErj2nk/Ocqxt4Ja8q21aoWLes4BBMQbr6k+iYvUSO2U7NagoTfG9uFue/oocsmETtOKDprAoGtrNhLM6ufFw1uRLuyThtrVaSbLBcLPEvg3we8XaUl90ADMRwq1jEjzslLv0G5gDqyac1qqSkL5h5CMNUHSokXYlySsuqB5JatylZGQ1ExlyYkrjBKQG2p2keTdrnpYEbMB8vkF6lL7mlaLXLyxULXqmlM29tZuZaEJsC0dQOQIXA/qsPNWw9hAfgT70Xz892Jb9ktr120uoEHmiq+mMvj+kolUg32rM5NcFt0NupissZUyJkphsmQ3VeQSi/nHI7v2pBNywHYjCdmarb4D+jTHQ3RwyqVG0lpmHoHcrpzfbgOcBH5+HSI5vDZNVv02Ki05w8om89xEIpeNRu6e8oM7i5x3uUueyZiKB2p/5l6wUdXf79PS8cw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
